version: '3.8'

services:
  quarkus-azure-functions:
    #    build:
    #      context: .                    # Directory dove si trova il Dockerfile
    #      dockerfile: Dockerfile        # Nome del Dockerfile (opzionale se si chiama "Dockerfile")
    image: mcr.microsoft.com/azure-functions/java:4-java17
    container_name: onboarding-fn
    tty: true
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    environment:
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005
      - QUARKUS_PROFILE=dev
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_PORT=8080
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - FUNCTIONS_WORKER_RUNTIME=java
      - MONGODB_CONNECTION_URI="mongodb://selc-d-cosmosdb-mongodb-account:OjIbF74Fce6fXsUFTx6uRnAok7XbQepzXTh9wCoQoVZruTxhGGiqKBCVaX6RGpUu69akUj376zEOACDblD9zoQ%3D%3D@selc-d-cosmosdb-mongodb-account.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@selc-d-cosmosdb-mongodb-account@"
      - USER_REGISTRY_API_KEY=9fypKNFfVY8jvWHUgABpH23VrChnRzvRpSq5b1ng
      - USER_REGISTRY_URL=https://api.uat.pdv.pagopa.it/user-registry/v1
      - BLOB_STORAGE_PRODUCT_CONNECTION_STRING="DefaultEndpointsProtocol=https/\;AccountName=selcdcheckoutsa/\;AccountKey=/\"mKXvgBvMgOepV/jLM4kIDq4KFJptUzhD7vvHHHtKnLuhIuPOTNfnT1iwnLphN2bdKcBwKR0SRN7V+AStcTYGgw==/\";EndpointSuffix=core.windows.net"
      - BLOB_STORAGE_CONN_STRING_CONTRACT="DefaultEndpointsProtocol=https/\;BlobEndpoint=https://selcdcontractsstorage.blob.core.windows.net/\;AccountName=selcdcontractsstorage/\;AccountKey=qLAv/9VatR42OF0WEt6WqjKSSHp9Sx+a1C8vSHQaIWyHOX6VnDJNIwhaADj685V+Dufbrx92tb3T+ASt6/e3AQ=="
      - AzureWebJobsScriptRoot=/home/site/wwwroot
    volumes:
      - .:/home/site/wwwroot
    #      # Mount del codice sorgente per sviluppo
    #      - ./src:/deployments/src:Z
    #      - ./target:/deployments/target:Z
    #      # Mount per i file di configurazione Azure Functions
    #      - ./local.settings.json:/deployments/local.settings.json:Z
    #      - ./host.json:/deployments/host.json:Z
    command: tail -f /dev/null
    networks:
      quarkus-network:
        # Assegna un IP statico a questo servizio
        ipv4_address: 172.20.0.10
    depends_on:
      - azurite

  # Azurite per emulare Azure Storage localmente
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite-storage
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    volumes:
      - azurite-data:/data
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data
    networks:
      quarkus-network:
        ipv4_address: 172.20.0.20


volumes:
  azurite-data:

networks:
  quarkus-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1