FROM maven:3.9.6-eclipse-temurin-17

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

ENV QUARKUS_CLI_VERSION=3.10.0 \
    NODE_VERSION=18.x
    
RUN apt-get update && \
    apt-get install -y curl unzip git && \
    curl -L https://github.com/quarkusio/quarkus/releases/download/${QUARKUS_CLI_VERSION}/quarkus-cli-${QUARKUS_CLI_VERSION}.tar.gz \
      | tar -xz -C /opt && \
    ln -s /opt/quarkus-cli-${QUARKUS_CLI_VERSION}/bin/quarkus /usr/local/bin/quarkus && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION} | bash - && \
    apt-get install -y nodejs

RUN apt-get update && apt-get install -y libicu70

WORKDIR /usr/src/app

RUN npm i -g azure-functions-core-tools@4 --unsafe-perm true
ENV AzureWebJobsScriptRoot=/usr/src/app AzureFunctionsJobHost__Logging__Console__IsEnabled=true

WORKDIR /app

RUN git clone https://github.com/pagopa/selfcare-onboarding.git

WORKDIR /app/selfcare-onboarding

COPY resources/fn/application.properties ./apps/onboarding-functions/src/main/resources/application.properties
COPY resources/fn/local.settings.json ./apps/onboarding-functions/local.settings.json
COPY resources/fn/host.json ./apps/onboarding-functions/host.json
COPY resources/fn/entrypoint.sh ./apps/onboarding-functions/entrypoint.sh

RUN mvn -pl apps/onboarding-functions -am clean install -DskipTests

WORKDIR /app/selfcare-onboarding/apps/onboarding-functions

RUN chmod +x entrypoint.sh
CMD ["./entrypoint.sh"]