FROM alpine/git AS git-stage
WORKDIR /repo
RUN git clone https://github.com/pagopa/selfcare-infra.git

FROM mcr.microsoft.com/azure-cli
COPY --from=git-stage /repo/selfcare-infra/src/core/resources /workspace/resources/resources

COPY initAzurite.sh /initAzurite.sh
RUN chmod +x ./initAzurite.sh
CMD ["/bin/sh", "-c", "/initAzurite.sh"]