package it.pagopa.selfcare.onboarding.common;

public enum WorkflowType {

    CONTRACT_REGISTRATION,//INSTITUTION
    FOR_APPROVE,//INSTITUTION
    FOR_APPROVE_PT,//INSTITUTION
    FOR_APPROVE_GPU,//INSTITUTION
    CONFIRMATION,//INSTITUTION
    USERS,//USER
    USERS_IMPORT,//USER
    IMPORT,//INSTITUTION
    IMPORT_AGGREGATION,
    CONTRACT_REGISTRATION_AGGREGATOR,//AGGREGATION
    CONFIRMATION_AGGREGATE,//AGGREGATION
    INCREMENT_REGISTRATION_AGGREGATOR,//AGGREGATION
    USERS_PG,//USER
    USERS_EA//USER
}
