package it.pagopa.selfcare.onboarding.common;

public enum WorkflowType {

    CONTRACT_REGISTRATION,//INSTITUTION
    FOR_APPROVE,//INSTITUTION
    FOR_APPROVE_PT,//INSTITUTION
    CONFIRMATION,//INSTITUTION
    USERS,//USER
    USERS_IMPORT,//USER
    IMPORT,//INSTITUTION
    CONTRACT_REGISTRATION_AGGREGATOR,//AGGREGATION
    CONFIRMATION_AGGREGATE,//AGGREGATION
    INCREMENT_REGISTRATION_AGGREGATOR,//AGGREGATION
    PG_USER//USER
}
