name: Check PR

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  labeler:
    name: Add label to PR based on the paths of files being changed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4

