on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      short_env:
        type: string
        required: true
        description: add '-pnpg' if workflow is related to pnpg

jobs:
  test:
    environment: ${{ inputs.environment }}-ci
    name: 'Run Postman collection on ${{ inputs.environment }}'
    runs-on: ubuntu-20.04
    # pool:
    #   name: $(selfHostedAgentPool)
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
      - name: 'Download postman environment'
        env: 
          INTEGRATION_ENVIRONMENT: ${{ secrets.INTEGRATION_ENVIRONMENT }}
        run: 'echo "$INTEGRATION_ENVIRONMENT" | base64 --decode > Selfcare-Integration.postman_environment.json'
        shell: bash
      - name: 'List file'
        run: 'ls -la'
        shell: bash
      - name: 'Cat file'
        run: 'cat Selfcare-Integration.postman_environment.json'
        shell: bash
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '16.x'

      - name: Install newman
        shell: bash
        run: npm install -g newman
      
      # run newman classic
      - name: Run newman
        shell: bash
        run:  newman run ./test/newman/Selfcare-Integration.postman_collection.json -e Selfcare-Integration.postman_environment.json --reporters cli,json --reporter-json-export ./test/test-result.json

      # - name: Install axios
      #   shell: bash
      #   run: npm install -g axios


      # - name: List modules installed
      #   shell: bash
      #   run: npm -g list

      - name: Send newman report
        shell: bash
        run:  node ./test/convert.js ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload-file-path: "./test/stats.json"
          payload-file-path-parsed: false
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    