name: Code Review onboarding-functions

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'apps/onboarding-functions/**'
  
  workflow_dispatch:

jobs:

  code-review:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps/onboarding-functions
            libs/
            test-coverage/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and analyze on Pull Requests
        shell: bash
        run: mvn --projects :test-coverage --also-make verify -Ponboarding-functions,report,coverage
          -Dsonar.organization=pagopa
          -Dsonar.projectKey=pagopa_selfcare-onboarding
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}