name: Create Release branch

on:
  workflow_dispatch:
    inputs:
      version-bump:
        required: false
        type: choice
        options:
          - major
          - minor
        default: minor

jobs:
  create_branch:
    name: 'Create Release Branch'
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
        with:
          ref: main

      - name: Get Current UAT version
        id: get-version
        shell: bash
        run: |
          run: echo "VERSION=$(git describe --match "releases/*" --abbrev=0 --tags | sed 's/releases\///')" >> $GITHUB_ENV

      - name: Bump Version
        id: bump-version
        shell: bash
        run: |
          echo "BUMPED_VERSION=$(semver bump ${{ inputs.version-bump }} ${{ steps.get-version.outputs.VERSION }})" >> $GITHUB_ENV

      - name: Set Branch Name
        id: set_branch
        shell: bash
        run: |
          echo "NEW_BRANCH_NAME=ag/${{ steps.bump-version.outputs.BUMPED_VERSION }}" >> $GITHUB_ENV

      - name: Create Branch
        shell: bash
        run: |
          git checkout -b $NEW_BRANCH_NAME

      - name: Push Branch
        shell: bash
        run: |
          git push origin $NEW_BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
