name: "Integration Tests (onboarding-fn)"

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "apps/onboarding-fn/**"
  workflow_dispatch:

jobs:
  integration_tests_fn:
    name: "Integration Tests (onboarding-fn)"
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Set up Docker Compose
        run: docker-compose -f apps/onboarding-functions/src/test/resources/docker-compose.yml up -d

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@fa2c7e4517ed008b1f73e7e0195a9eecf5582cd4
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: "temurin"
          maven-version: "3.9.5"
          cache-enabled: true

      - uses: s4u/maven-settings-action@60912582505985be4cc55d2b890eb32767f8de5f
        with:
          servers: '[{"id": "selfcare-github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

      - name: Build project
        shell: bash
        run: mvn clean install
        working-directory: apps/onboarding-functions
