name: Deploy onboarding functions

on:
  pull_request:
    branches:
      - develop
      - main
    types: [closed]
    paths:
      - "apps/onboarding-functions/**"
      - "apps/pom.xml"

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod

env:
  #DIR: "./.container_apps/onboarding-ms"
  # This condition (that unfortunately must be replicated for the first job)
  # sets the environment depending on the current context for manually
  # started workflows, it picks up the value coming from the UI; otherwise,
  # it sets prod or uat depending on the current branch.
  # Ternary operator is not supported
  ENV_NAME: "${{ inputs.environment != null && inputs.environment || (github.base_ref == 'main' && 'prod' || (github.base_ref == 'develop' && 'uat' || 'dev')) }}"

jobs:
  build:
    name: Build Onboarding Functions
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == 'true') }}
    environment: "${{ inputs.environment != null && inputs.environment || (github.base_ref == 'main' && 'prod' || (github.base_ref == 'develop' && 'uat' || 'dev')) }}-cd"
    outputs:
      environment: ${{ steps.setenv.outputs.environment }}
      short_sha: ${{ steps.setsha.outputs.short_sha }}
    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: ${{ github.ref_name }}

      # this workaround is necessary to pass the environment value to the next job
      # unexpectly, global env vars cannot be read to set the environment and I don't
      # want to repeat that complex expression (already repeated twice)
      - name: Read Environment
        id: setenv
        shell: bash
        run: |
          echo "environment=$ENV_NAME" >> $GITHUB_OUTPUT

      # github doesn't provide a short sha anymore
      - name: Set Short Git Commit SHA
        id: setsha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=sha-$calculatedSha" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: "Build Functions and dependencies"
        shell: bash
        run: mvn --projects :onboarding-functions --also-make package -DskipTests

      - name: Log in to Azure
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Deploy Functions"
        shell: bash
        run: mvn -f apps/onbording-functions/pom.xml quarkus:deploy 
          -Dquarkus.azure-functions.app-name=${{ vars.AZURE_ONBOARDING_FN_APP_NAME }}
          -Dquarkus.azure-functions.subscription-id=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          -Dquarkus.azure-functions.resource-group=${{ vars.AZURE_ONBOARDING_FN_RESOURCE_GROUP }}
          -Dquarkus.azure-functions.region=westeurope
          -Dquarkus.azure-functions.app-service-plan-name=${{ vars.AZURE_ONBOARDING_FN_SERVICE_PLAN }}
          -Dquarkus.azure-functions.runtime.java-version=17

