name: Integration test

on:
  push:
    branches:
      - main
      - releases/*

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat

jobs:

  test_dev:
    uses: ./.github/workflows/call_integration_test.yml
    name: '[Dev] Integration test'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      short_env: d


