name: Code Review Libs

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'libs/**'
      - '.github/workflows/code_review_libs.yml'
      - '.github/workflows/call_code_review.yml'

jobs:

  code_review:
    uses: ./.github/workflows/call_code_review.yml
    name: Libs Code Review
    secrets: inherit
    with:
      pr_number: ${{ github.event.pull_request.number }}
      source_branch: ${{ github.head_ref }}
      target_branch: ${{ github.base_ref }}
      sonar_key: 'pagopa_selfcare-onboarding'
