name: Release Onboarding

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat
          - prod

jobs:
  create_branch:
    name: 'Create Release Branch'
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      actions: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
        with:
          ref: main
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1

      - name: Install semver
        run: npm install -g semver

      - name: Trigger Functions Infra Release
        run: |
          gh workflow run release_functions_infra.yml \
            --ref ${{ inputs.env }}

      - name: Trigger Mongo Infra Release
        run: |
          gh workflow run release_mongo_infra.yml \
            --ref ${{ inputs.env }}

      - name: Trigger PNPG Functions Infra Release
        run: |
          gh workflow run release_functions_pnpg_infra.yml \
            --ref ${{ inputs.env }}

      - name: Trigger PNPG Mongo Infra Release
        run: |
          gh workflow run release_mongo_pnpg_infra.yml \
            --ref ${{ inputs.env }}

      - name: Trigger Functions Release
        run: |
          gh workflow run release_functions.yml \
            --ref ${{ inputs.env }}

      - name: Trigger Onboarding ms Release
        run: |
          gh workflow run release_ms.yml \
            --ref ${{ inputs.env }}

      - name: Trigger Onboarding CDC Release
        run: |
          gh workflow run release_cdc.yml \
            --ref ${{ inputs.env }}

      - name: Trigger PNPG Functions Release
        run: |
          gh workflow run release_pnpg_functions.yml \
            --ref ${{ inputs.env }}

      - name: Trigger PNPG Onboarding ms Release
        run: |
          gh workflow run release_pnpg_ms.yml \
            --ref ${{ inputs.env }}

      - name: Trigger PNPG Onboarding CDC Release
        run: |
          gh workflow run release_pnpg_cdc.yml \
            --ref ${{ inputs.env }}