name: Deploy PNPG functions infra

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - './infra/functions/onboarding-functions/env/dev-pnpg'
      - './infra/functions/onboarding-functions/env/uat-pnpg'
      - './infra/functions/onboarding-functions/env/prod-pnpg'
      - '!./infra/functions/onboarding-functions/env/**'
      - './infra/functions/onboarding-functions/**'

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

jobs:

  release_dev:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Dev] Functions Infra Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev-pnpg
      dir: ./infra/functions/onboarding-functions

  release_uat:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[UAT] Functions Infra Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat-pnpg
      dir: ./infra/functions/onboarding-functions

  release_prod:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Prod] Functions Infra Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod-pnpg
      dir: ./infra/functions/onboarding-functions
