name: Release Onboarding

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat
          - prod

jobs:
  create_branch:
    name: 'Create Release Branch'
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      actions: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      $GITHUB_BRANCH_NAME: ${{ github.ref }}
    
    steps:
      # - name: Detect branch name
      #   shell: bash
      #   run: echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_BRANCH_NAME
      #   id: extract_branch
      
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
        with:
          ref: main
          fetch-depth: 0

      - name: Trigger Functions Infra Release
        run: |
          gh workflow run release_functions_infra.yml \
            --ref $GITHUB_BRANCH_NAME

      - name: Trigger Mongo Infra Release
        run: |
          gh workflow run release_mongo_infra.yml \
            --repo pagopa/selfcare-onboarding \
            --ref ${{ inputs.branch }}

      - name: Trigger PNPG Functions Infra Release
        run: |
          gh workflow run release_functions_pnpg_infra.yml \
            --repo pagopa/selfcare-onboarding \
            --ref ${{ inputs.branch }}

      - name: Trigger PNPG Mongo Infra Release
        run: |
          gh workflow run release_mongo_pnpg_infra.yml \
            --repo pagopa/selfcare-onboarding \
            --ref ${{ inputs.branch }}

      - name: Trigger Functions Release
        run: |
          gh workflow run release_functions.yml \
            --repo pagopa/selfcare-onboarding \
            --ref ${{ inputs.branch }}

      - name: Trigger Onboarding ms Release
        run: |
          gh workflow run release_ms.yml \
            --ref ${{ inputs.env }}

      - name: Trigger Onboarding CDC Release
        run: |
          gh workflow run release_cdc.yml \
            --repo pagopa/selfcare-onboarding \
            --ref ${{ inputs.branch }}

      - name: Trigger PNPG Functions Release
        run: |
          gh workflow run release_pnpg_functions.yml \
            --repo pagopa/selfcare-onboarding \
            --ref ${{ inputs.branch }}

      - name: Trigger PNPG Onboarding ms Release
        run: |
          gh workflow run release_pnpg_ms.yml \
            --repo pagopa/selfcare-onboarding \
            --ref ${{ inputs.branch }}

      - name: Trigger PNPG Onboarding CDC Release
        run: |
          gh workflow run release_pnpg_cdc.yml \
            --repo pagopa/selfcare-onboarding \
            --ref ${{ inputs.branch }}