name: Deploy functions infra

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - './infra/functions/onboarding-functions/**'

  workflow_dispatch:

jobs:

  release_dev:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Dev] Functions Infra Release'
    if: github.ref_name == 'main'
    secrets: inherit
    with:
      environment: dev
      dir: ./infra/functions/onboarding-functions

  release_uat:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[UAT] Functions Infra Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: uat
      dir: ./infra/functions/onboarding-functions

  release_prod:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Prod] Functions Infra Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: prod
      dir: ./infra/functions/onboarding-functions
