name: Infra integration test

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - './infra/resources/**'

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat
          - prod

jobs:

  release_dev:
    uses: ./.github/workflows/call_release_resources_infra.yml
    name: '[Dev] Functions Resources Infra Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      dir: ./infra/resources/dev

  release_uat:
    uses: ./.github/workflows/call_release_resources_infra.yml
    name: '[UAT] Functions Resources Infra Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      dir: ./infra/resources/uat

  release_prod:
    uses: ./.github/workflows/call_release_resources_infra.yml
    name: '[Prod] Functions Resources Infra Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      dir: ./infra/resources/prod
