name: Release Onboarding

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat
          - prod
      branch:
        type: string
        description: Branch name
        required: true

jobs:
  create_branch:
    name: 'Create Release Branch'
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      actions: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@1fb4a623cfbc661771f7005e00e2cf74acf32037 # v4.2.2
        name: Checkout
        with:
          ref: main
          fetch-depth: 0

      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Trigger Functions Infra Release
        run: |
          gh workflow run release_functions_infra.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger Mongo Infra Release
        run: |
          gh workflow run release_mongo_infra.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger PNPG Functions Infra Release
        run: |
          gh workflow run release_functions_pnpg_infra.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger PNPG Mongo Infra Release
        run: |
          gh workflow run release_mongo_pnpg_infra.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger Functions Release
        run: |
          gh workflow run release_functions.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger Onboarding ms Release
        run: |
          gh workflow run release_ms.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger Onboarding CDC Release
        run: |
          gh workflow run release_cdc.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger PNPG Functions Release
        run: |
          gh workflow run release_pnpg_functions.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger PNPG Onboarding ms Release
        run: |
          gh workflow run release_pnpg_ms.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}

      - name: Trigger PNPG Onboarding CDC Release
        run: |
          gh workflow run release_pnpg_cdc.yml \
            --ref ${{ steps.get_branch.outputs.BRANCH_NAME }}