name: Swagger Detect Conflict and Update
on:
  pull_request:
    branches:
      - main
      - releases/*
    types: [ opened, synchronize, reopened ]
    paths:
      - "apps/onboarding-ms/**"
    
permissions:
  contents: write

jobs:
  swagger_conflict_update:  
    name: Swagger Detect Conflict and Update
    id: swagger-conflict-update
    uses: pagopa/selfcare-commons/github-actions-template/swagger-detect-conflict-quarkus@1fae5bea1f32f4106f6026166a47e5daa122b82a
    with:
      path_openapi_docs: src/main/docs
      branch_ref: main
      module: onboarding-ms