name: Swagger Detect Conflict and Update
on:
  pull_request:
    branches:
      - main
      - releases/*
    types: [ opened, synchronize, reopened ]
    paths:
      - "apps/onboarding-ms/**"
    
permissions:
  contents: write

jobs:
  swagger_conflict_update:  
    name: Swagger Detect Conflict and Update
    id: swagger-conflict-update
    uses: pagopa/selfcare-commons/github-actions-template/swagger-detect-conflict-quarkus@fa7b6f4e9620ce6c072ac50c08f0d09aaf4b2e62
    with:
      path_openapi_docs: src/main/docs
      branch_ref: main
      module: onboarding-ms